import Head from 'next/head'
import Image from 'next/image'
import * as Dialog from '@radix-ui/react-dialog';
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [scaleIndex, setScaleIndex] = useState(1)
  const sizes = ['scale-50', 'scale-100', 'scale-150']

  useEffect(() => {
    console.log("size changed = " + scaleIndex)
  }, [scaleIndex])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='h-screen bg-zinc-900'>
        <div className='fixed top-0'>
          <Dialog.Root>
            <Dialog.Trigger asChild>
              <button className="bg-white rounded-full p-4">
                ?
              </button>
            </Dialog.Trigger>
            <Dialog.Portal>
              <Dialog.Overlay className='bg-black fixed inset-0 opacity-50' />
              <Dialog.Content className='bg-white w-1/2 h-1/2 fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2'>
                <Dialog.Title>test</Dialog.Title>
                <Dialog.Description>testoayldj;kbas</Dialog.Description>
                <Dialog.Close asChild>
                  <button className="bg-white rounded-full p-4">
                    Close
                  </button>
                </Dialog.Close>
              </Dialog.Content>
            </Dialog.Portal>
          </Dialog.Root>
        </div>
        <div className='flex flex-col min-h-full justify-around items-center'>
          <div className='flex flex-col justify-center items-center gap-2'>
            <div className='rounded-full bg-white w-32 h-32'/>
            <div className='bg-white w-32 h-48'/>
            <div className={`rounded-full bg-white w-32 h-32 ${sizes[scaleIndex]} transition-transform duration-500`}/>
          </div>
          <div className='flex justify-center items-center gap-8'>
            <button className='bg-white rounded-lg p-4 hover:scale-110 disabled:opacity-50 transition-all duration-300' onClick={() => setScaleIndex(scaleIndex - 1)} disabled={scaleIndex === 0}>Decrease Star Size</button>
            <button className='bg-white rounded-lg p-4 hover:scale-110 disabled:opacity-50 transition-all duration-300' onClick={() => setScaleIndex(scaleIndex + 1)} disabled={scaleIndex === 2}>Increase Star Size</button>
          </div>
        </div>
      </div>

    </>
  )
}
